"""Apply the agreed analysis scope: 2007-2023.

Run:      cd Code && uv run python 02_select_scope.py
Reads:    Attachments/DataForTable2.1.xls
Produces: Code/outputs/whr_2007_2023.csv   the working dataset
          Code/outputs/scope.md            what the restriction keeps and costs

Why 2007-2023. 2005 holds 27 countries and exactly one row with every column present.
2006 holds 89 countries at 83% completeness, the weakest of any usable year. From 2007
the panel is 102+ countries at 89-93% complete every year. Starting at 2007 keeps 17
consecutive years without carrying the two thin ones.

Selects and adds one derived column; cleans nothing, imputes nothing, and leaves the
published column names untouched so the working dataset stays traceable to the source.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

CODE_DIR = Path(__file__).resolve().parent
ROOT = CODE_DIR.parent
SOURCE = ROOT / "Attachments" / "DataForTable2.1.xls"
OUTPUTS = CODE_DIR / "outputs"

FIRST_YEAR, LAST_YEAR = 2007, 2023

COUNTRY, YEAR, LADDER = "Country name", "year", "Life Ladder"
GDP_LOG = "Log GDP per capita"
GDP_USD = "GDP per capita (PPP 2017 int$)"   # derived, added by this script
HLE = "Healthy life expectancy at birth"

# The five variables most analyses will need. Corruption and generosity are the
# sparsest columns, so a balanced panel is reported both with and without them.
KEY = [LADDER, GDP_LOG, "Social support", HLE, "Freedom to make life choices"]

lines: list[str] = []


def out(text: str = "") -> None:
    lines.append(text)


def table(df: pd.DataFrame) -> None:
    out()
    out(df.to_markdown(index=False))
    out()


def main() -> int:
    OUTPUTS.mkdir(exist_ok=True)
    full = pd.read_excel(SOURCE)
    core = [c for c in full.columns if c not in (COUNTRY, YEAR)]

    keep = full[(full[YEAR] >= FIRST_YEAR) & (full[YEAR] <= LAST_YEAR)].copy()
    dropped = full[(full[YEAR] < FIRST_YEAR) | (full[YEAR] > LAST_YEAR)]

    # Derived: GDP in dollars. The source stores a natural log, which is hard to read.
    # Lossless and reversible; the original column is retained alongside.
    keep.insert(keep.columns.get_loc(GDP_LOG) + 1, GDP_USD, np.exp(keep[GDP_LOG]))

    keep["complete"] = keep[core].notna().all(axis=1)
    keep["key_ok"] = keep[KEY].notna().all(axis=1)

    out(f"# Analysis Scope — {FIRST_YEAR} to {LAST_YEAR}")
    out()
    out("Generated by `Code/02_select_scope.py`. Selection plus one derived column; "
        "nothing cleaned, altered or imputed.")

    # ---------------------------------------------------------------- decision
    out()
    out("## Decision")
    out()
    out(f"Keep `{FIRST_YEAR} <= year <= {LAST_YEAR}`.")
    out()
    out("Reason: 2005 holds 27 countries and exactly one row with every column "
        "present, and 2006 holds 89 countries at 83% completeness — the weakest of "
        f"any usable year. From {FIRST_YEAR} the panel runs at 102 or more countries "
        "and 86–93% completeness every year. This keeps 17 consecutive years without "
        "carrying the two thin ones.")

    # ---------------------------------------------------------------- keeps
    out()
    out("## What the restriction keeps")
    out()
    out(f"- Rows: {len(keep):,} of {len(full):,} ({len(keep) / len(full):.0%}).")
    out(f"- Years: {keep[YEAR].nunique()} consecutive, {FIRST_YEAR}–{LAST_YEAR}, "
        "no gaps.")
    out(f"- Countries: {keep[COUNTRY].nunique()}.")
    out(f"- Rows with every column present: {int(keep['complete'].sum()):,} "
        f"({keep['complete'].mean():.0%}).")
    out(f"- Rows with all five key variables present: "
        f"{int(keep['key_ok'].sum()):,} ({keep['key_ok'].mean():.0%}).")

    out()
    out("### Columns in scope")
    rows = []
    for c in keep.columns:
        if c in ("complete", "key_ok"):
            continue
        r = {"column": c, "non-null": int(keep[c].notna().sum()),
             "missing": int(keep[c].isna().sum())}
        if pd.api.types.is_numeric_dtype(keep[c]):
            r["min"] = round(float(keep[c].min()), 3)
            r["max"] = round(float(keep[c].max()), 3)
        else:
            r["min"] = r["max"] = ""
        rows.append(r)
    table(pd.DataFrame(rows))
    out(f"`{GDP_USD}` is derived by this script as `exp({GDP_LOG})`. The log is "
        "retained because equal increments in it correspond to equal *proportional* "
        "differences in income, which is often what a model should use.")

    out()
    out("### Coverage by year")
    per_year = (keep.groupby(YEAR)
                    .agg(countries=(COUNTRY, "nunique"),
                         complete=("complete", "sum"),
                         key_ok=("key_ok", "sum"))
                    .reset_index())
    per_year["% complete"] = (per_year["complete"] / per_year["countries"] * 100).round(0).astype(int)
    per_year.columns = ["Year", "Countries", "Complete rows", "Rows with key 5",
                        "% complete"]
    table(per_year)

    obs = keep.groupby(COUNTRY)[YEAR].nunique()
    n_years = keep[YEAR].nunique()
    out(f"- Years observed per country: min {int(obs.min())}, "
        f"median {int(obs.median())}, max {int(obs.max())}.")
    out(f"- Present in all {n_years} years, at any completeness: "
        f"{int((obs == n_years).sum())} countries.")

    # ------------------------------------------------------- balanced options
    out()
    out("## Balanced-panel options inside the scope")
    out()
    out("A balanced panel — the same countries in every year — is needed for some "
        "comparisons over time and not for others. The cost is country count.")
    out()
    rows = []
    for label, flag in (("every column present", "complete"),
                        ("five key variables present", "key_ok")):
        sub = keep[keep[flag]]
        n = sub.groupby(COUNTRY)[YEAR].nunique()
        cty = int((n == n_years).sum())
        rows.append({"requirement": label, "countries in all years": cty,
                     "country-years": cty * n_years})
    table(pd.DataFrame(rows))

    bal = keep[keep["complete"]]
    nb = bal.groupby(COUNTRY)[YEAR].nunique()
    members = sorted(nb[nb == n_years].index)
    out(f"The {len(members)} countries with every column present in all {n_years} "
        "years:")
    out()
    out("> " + ", ".join(members))
    out()
    # Is that subset representative? Compare on the two headline variables.
    last = keep[keep[YEAR] == LAST_YEAR]
    inb = last[last[COUNTRY].isin(members)]
    outb = last[~last[COUNTRY].isin(members)]
    out(f"That subset is not obviously skewed: in {LAST_YEAR} its median GDP per "
        f"capita is ${inb[GDP_USD].median():,.0f} against "
        f"${outb[GDP_USD].median():,.0f} for the excluded countries, and its median "
        f"life ladder {inb[LADDER].median():.2f} against {outb[LADDER].median():.2f}. "
        "It does span rich and poor.")
    out()
    absent = [c for c in ["United States", "China", "Germany", "France", "Japan",
                          "Brazil", "Canada", "Australia", "Nigeria"]
              if c in set(keep[COUNTRY]) and c not in members]
    if absent:
        out(f"It does, however, exclude several of the largest economies — "
            f"{', '.join(absent)} — each of which is missing at least one value in at "
            "least one year. A strictly balanced panel would leave them out, which is "
            "worth weighing against whatever it buys.")

    # ---------------------------------------------------------------- missing
    out()
    out("## Missing data")
    out()
    out("Gaps are **not** spread evenly. They concentrate in particular countries, and "
        "for one column they are plausibly caused by the very thing being measured.")
    out()
    gap = keep.copy()
    gap["nmiss"] = gap[[c for c in core if c in gap.columns]].isna().sum(axis=1)
    worst = (gap.groupby(COUNTRY)
                .agg(rows=(YEAR, "size"), missing_cells=("nmiss", "sum"))
                .sort_values("missing_cells", ascending=False).head(10)
                .reset_index())
    out("Countries with the most missing cells:")
    table(worst)

    # A column with no observations at all for a country cannot be interpolated
    # from that country's own data - only guessed from other countries.
    out("Columns missing in **every** year a country appears — nothing within that "
        "country to interpolate from:")
    out()
    any_total = keep.groupby(COUNTRY).size()
    for col in core:
        if col not in keep.columns:
            continue
        m = keep[keep[col].isna()].groupby(COUNTRY).size()
        always = sorted(m[m == any_total.reindex(m.index)].index)
        if always:
            out(f"- `{col}`: {', '.join(always)}")
    out()

    with_gap = gap[gap["nmiss"] > 0]
    no_gap = gap[gap["nmiss"] == 0]
    out(f"Rows with a gap are not poorer or unhappier than complete rows — median life "
        f"ladder {with_gap[LADDER].median():.2f} against "
        f"{no_gap[LADDER].median():.2f}, median GDP "
        f"${with_gap[GDP_USD].median():,.0f} against ${no_gap[GDP_USD].median():,.0f}. "
        "That is reassuring about income, but says nothing about the mechanism: the "
        "corruption questions were not asked in several states where asking would be "
        "politically sensitive, which is missingness caused by the subject itself.")
    out()
    out(f"Note also that `{HLE}` is interpolated and extrapolated by WHR to cover years "
        "the WHO series does not reach, so part of that column is already model output "
        "rather than measurement.")
    out()
    out("**Handling, decided 2026-09-07: no imputation.** Values are left missing. Each "
        "analysis uses whatever rows carry the variables it needs, on an unbalanced "
        "panel — a balanced panel is not required. Where a variable is systematically "
        "absent, the excluded countries are named and the likely bias stated, rather "
        "than a number being invented for them.")

    # ---------------------------------------------------------------- costs
    out()
    out("## What the restriction costs")
    out()
    lost = sorted(set(dropped[COUNTRY]) - set(keep[COUNTRY]))
    out(f"- {len(dropped):,} rows from "
        f"{sorted(int(y) for y in dropped[YEAR].unique())}.")
    out(f"- Countries lost entirely: {len(lost) if lost else 'none'}"
        + (f" — {', '.join(lost)}." if lost else "."))
    out("- Two years of history, both of them thin. Nothing else.")

    # ------------------------------------------------------- residual defects
    out()
    out("## Defects that remain inside the scope")
    out()
    haiti = keep[(keep[COUNTRY] == "Haiti") & (keep[HLE] < 40)]
    if not haiti.empty:
        out(f"- Haiti's `{HLE}` is still corrupted in {len(haiti)} rows:")
        table(haiti[[COUNTRY, YEAR, HLE]].round(2))
    ven = keep[keep[COUNTRY] == "Venezuela"].nsmallest(3, GDP_USD)
    if not ven.empty:
        out(f"- Venezuelan GDP remains implausible, as low as "
            f"${ven[GDP_USD].min():,.0f} per capita in "
            f"{int(ven.loc[ven[GDP_USD].idxmin(), YEAR])}.")
    out(f"- {LAST_YEAR} GDP is partly **forecast**, not measured: the WHR 2024 "
        "appendix states 2023 GDP per capita was unavailable when the file was built "
        "and was extended from 2022 using OECD and World Bank growth forecasts. "
        f"{LAST_YEAR} also has the most missing GDP of any year in scope.")
    out()
    out("None of these have been altered. Whether to exclude or correct them is a "
        "cleaning decision, not yet taken.")

    # ---------------------------------------------------------------- write
    csv = OUTPUTS / f"whr_{FIRST_YEAR}_{LAST_YEAR}.csv"
    keep.drop(columns=["complete", "key_ok"]).to_csv(csv, index=False)
    out()
    out("## Output")
    out()
    out(f"`outputs/{csv.name}` — {len(keep):,} rows × "
        f"{keep.shape[1] - 2} columns (the source's 11, plus the derived "
        "dollar column).")

    path = OUTPUTS / "scope.md"
    path.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {path} and {csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
