"""Apply agreed cleaning rules to the scoped dataset.

Run:      cd Code && uv run python 03_clean.py
Reads:    Code/outputs/whr_2007_2023.csv
Produces: Code/outputs/whr_clean.csv   the analysis dataset
          Code/outputs/cleaning.md     every rule, its reason, and what it changed

Cleaning here means one thing only: setting values that are known to be wrong to
missing. Nothing is imputed, corrected or overwritten with an estimate - the project
decision is to leave gaps as gaps. Every rule is declared in RULES below with a
reason, and the report states exactly which rows each one touched.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

CODE_DIR = Path(__file__).resolve().parent
OUTPUTS = CODE_DIR / "outputs"
SOURCE = OUTPUTS / "whr_2007_2023.csv"

COUNTRY, YEAR = "Country name", "year"
HLE = "Healthy life expectancy at birth"
GDP_LOG, GDP_USD = "Log GDP per capita", "GDP per capita (PPP 2017 int$)"


@dataclass
class Rule:
    """One cleaning rule: blank these columns for this country in these years."""
    country: str
    columns: list[str]
    years: list[int] | None          # None = every year in scope
    reason: str
    decided: str


RULES: list[Rule] = [
    Rule(
        country="Haiti",
        columns=[HLE],
        years=[2008, 2010, 2011, 2012, 2013, 2014],
        reason=(
            "The whole span is a broken backwards extrapolation. From 2010 to 2015 the "
            "series rises in exact steps of +5.32 years per year (17.36, 28.00, 33.32, "
            "38.64, 43.96, 49.28, 54.60), reaching 54.60 in 2015, after which the steps "
            "become +0.30. A constant increment is what linear interpolation between two "
            "anchors produces, and the change of step locates the anchor: 2015 is "
            "observed, everything before it on the ramp is constructed. Haiti's true "
            "healthy life expectancy over this period is around 55 years, so the early "
            "values are also implausible on their own terms. 2015 onwards is kept."
        ),
        decided="2026-09-07 (extended from [2008, 2010, 2011, 2012] the same day: the "
                "first version blanked only values below 40 years, which left 2013 "
                "(43.96) and 2014 (49.28) on the same fabricated ramp)",
    ),
    Rule(
        country="Venezuela",
        columns=[GDP_LOG, GDP_USD],
        years=None,
        reason=(
            "The series falls from $19,197 in 2012 to $251 in 2019, a cumulative 98.7% "
            "collapse, ending far below the poorest country in the panel (Niger at "
            "$1,217 in the same year, Burundi at $740 at its lowest). Venezuela's real "
            "contraction was severe but nearer 75-80%. WHR takes Venezuelan GDP from "
            "the Penn World Table rather than the World Bank; Venezuela stopped "
            "publishing national accounts around 2014 and then experienced "
            "hyperinflation, so any price-based conversion explodes. The divergence "
            "grows from about 2014 with no clean breakpoint visible inside the file, so "
            "the whole series is blanked rather than a cut-off being guessed. Only GDP "
            "is affected - the survey-based measures are unaffected and are kept."
        ),
        decided="2026-09-07",
    ),
]

lines: list[str] = []


def out(text: str = "") -> None:
    lines.append(text)


def table(df: pd.DataFrame) -> None:
    out()
    out(df.to_markdown(index=False))
    out()


def main() -> int:
    df = pd.read_csv(SOURCE)
    before = df.copy()

    out("# Cleaning")
    out()
    out("Generated by `Code/03_clean.py`. Cleaning here means **setting known-wrong "
        "values to missing**. Nothing is imputed, estimated or overwritten.")

    out()
    out("## Rules applied")

    total = 0
    for rule in RULES:
        mask = df[COUNTRY] == rule.country
        if rule.years is not None:
            mask &= df[YEAR].isin(rule.years)
        affected = df[mask]
        out()
        out(f"### {rule.country} — `{'`, `'.join(rule.columns)}`")
        out()
        span = ("every year in scope" if rule.years is None
                else ", ".join(str(y) for y in rule.years))
        out(f"- **Years:** {span}")
        out(f"- **Decided:** {rule.decided}")
        out(f"- **Reason:** {rule.reason}")
        out()
        # Count only cells that actually held a value, so the audit trail is not
        # inflated by rows that were already blank.
        n_values = int(sum(df.loc[mask, c].notna().sum() for c in rule.columns))
        already = int(mask.sum()) * len(rule.columns) - n_values
        shown = affected.loc[affected[rule.columns].notna().any(axis=1),
                             [COUNTRY, YEAR] + rule.columns].round(2)
        if not mask.any():
            out("- **Effect:** no matching rows — the rule changed nothing. Check it "
                "is still needed.")
        elif n_values == 0:
            out(f"- **Effect:** {int(mask.sum())} row(s) matched but every targeted "
                "cell was already missing. The rule changed nothing.")
        else:
            out(f"- **Effect:** {n_values} value(s) blanked across {len(shown)} row(s)"
                + (f"; a further {already} targeted cell(s) were already missing."
                   if already else "."))
            table(shown)
        for col in rule.columns:
            df.loc[mask, col] = pd.NA
        total += n_values

    # ---------------------------------------------------------------- effect
    out("## Net effect")
    out()
    out(f"- {total} value(s) set to missing across {len(RULES)} rule(s).")
    out(f"- Rows: {len(df):,} — unchanged. No row is dropped; only cells are blanked, "
        "so a country keeps every other variable for that year.")

    changed = []
    for col in df.columns:
        b, a = int(before[col].isna().sum()), int(df[col].isna().sum())
        if b != a:
            changed.append({"column": col, "missing before": b, "missing after": a})
    if changed:
        table(pd.DataFrame(changed))

    # ------------------------------------------------------- known, not cleaned
    out("## Known problems deliberately left in place")
    out()
    out("- **2023 GDP is partly forecast.** The WHR 2024 appendix states 2023 GDP per "
        "capita was unavailable when the file was built and was extended from 2022 "
        "using OECD and World Bank growth forecasts. Accepted as-is (decided "
        "2026-09-07): a forecast one year ahead is a reasonable estimate, and dropping "
        "2023 would cost the most recent year of the panel. Any result that leans on "
        "2023 GDP should say so.")
    out(f"- **`{HLE}` is interpolated throughout.** WHR extends the WHO series to "
        "cover the sample period, so this column is part measurement and part model "
        "output for every country, not only Haiti.")

    ven = df[(df[COUNTRY] == "Venezuela") & df[GDP_USD].notna()]
    if not ven.empty:
        out(f"- **Venezuelan GDP is unresolved.** The series falls from "
            f"${ven[GDP_USD].max():,.0f} to ${ven[GDP_USD].min():,.0f} per capita, a "
            "collapse of over 98%, and the lowest values sit far below the poorest "
            "country in the panel. No rule has been agreed yet.")

    csv = OUTPUTS / "whr_clean.csv"
    df.to_csv(csv, index=False)
    out()
    out("## Output")
    out()
    out(f"`outputs/{csv.name}` — {len(df):,} rows × {df.shape[1]} columns. This is the "
        "dataset later steps should read.")

    path = OUTPUTS / "cleaning.md"
    path.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {path} and {csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
