"""Sub-question 1, step 3: build the cross-section for the scatter.

Run:      cd Code && uv run python 04_sq1_scatter.py
Reads:    Code/outputs/whr_clean.csv
Produces: Code/outputs/latest_by_country.csv   one row per country, its most recent year
          Code/outputs/sq1_scatter.md          what the cross-section is

The figure itself is drawn by 05_sq1_regression.py, which has the fitted line to put
on it. This script defines and documents the data that goes into it.

Cross-section. One row per country: its **most recent year in which both variables are
present**. That is not the same year for every country, because coverage ends earlier for
some, so the mix of years is reported rather than assumed away.

Deliberately no fitted line. Quantifying the relationship is step 4, and whether a
straight line describes it at all was a question set aside without being tested -
drawing one here would answer it by assumption before it had been put.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

CODE_DIR = Path(__file__).resolve().parent
OUTPUTS = CODE_DIR / "outputs"
SOURCE = OUTPUTS / "whr_clean.csv"

COUNTRY, YEAR = "Country name", "year"
LADDER = "Life Ladder"
HLE = "Healthy life expectancy at birth"

lines: list[str] = []


def out(text: str = "") -> None:
    lines.append(text)


def table(df: pd.DataFrame) -> None:
    out()
    out(df.to_markdown(index=False))
    out()


def main() -> int:
    df = pd.read_csv(SOURCE)
    both = df[df[LADDER].notna() & df[HLE].notna()]

    # Most recent year per country in which BOTH variables are present.
    cs = (both.sort_values(YEAR)
               .groupby(COUNTRY, as_index=False)
               .tail(1)
               .sort_values(COUNTRY)
               .reset_index(drop=True))

    out("# Sub-question 1 — cross-section and scatter")
    out()
    out("Generated by `Code/04_sq1_scatter.py`. Description and one figure; nothing is "
        "quantified here.")

    out()
    out("## The cross-section")
    out()
    out(f"One row per country, at its **most recent year in which both `{LADDER}` and "
        f"`{HLE}` are present**.")
    out()
    out(f"- Countries: **{len(cs)}** of {df[COUNTRY].nunique()} in the cleaned panel.")
    excluded = sorted(set(df[COUNTRY]) - set(cs[COUNTRY]))
    out(f"- Excluded: {len(excluded)} — {', '.join(excluded)}. Each lacks healthy life "
        "expectancy in every year, so no cross-section row exists for it.")
    out(f"- `{LADDER}` range {cs[LADDER].min():.2f}–{cs[LADDER].max():.2f}; "
        f"`{HLE}` range {cs[HLE].min():.1f}–{cs[HLE].max():.1f} years.")

    out()
    out("## Which year each country contributes")
    out()
    out("The most recent year is **not** the same for every country. A country whose "
        "coverage stops early contributes an older observation, so this cross-section "
        "mixes years and is not a snapshot of any single one.")
    yr = (cs.groupby(YEAR).agg(countries=(COUNTRY, "size")).reset_index()
            .sort_values(YEAR, ascending=False))
    yr.columns = ["Year", "Countries"]
    table(yr)
    latest = int(cs[YEAR].max())
    n_latest = int((cs[YEAR] == latest).sum())
    out(f"- {n_latest} of {len(cs)} countries ({n_latest / len(cs):.0%}) contribute "
        f"{latest}.")
    older = cs[cs[YEAR] < latest]
    if not older.empty:
        out(f"- {len(older)} contribute an earlier year, the oldest being "
            f"{int(older[YEAR].min())}:")
        table(older.sort_values(YEAR)[[COUNTRY, YEAR, LADDER, HLE]]
                   .round({LADDER: 2, HLE: 1})
                   .rename(columns={COUNTRY: "Country", YEAR: "Year",
                                    LADDER: "Ladder", HLE: "HLE (years)"}))
        out("Whether to keep these or restrict to a single year is a decision for the "
            "user; both are reported so the choice is visible.")

    out()
    out("The figure built from this cross-section is drawn by `05_sq1_regression.py`, "
        "which fits the line that goes on it.")

    csv = OUTPUTS / "latest_by_country.csv"
    cs.to_csv(csv, index=False)
    out()
    out("## Output")
    out()
    out(f"`outputs/{csv.name}` — {len(cs)} rows, the cross-section used above.")

    path = OUTPUTS / "sq1_scatter.md"
    path.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {path} and {csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
