"""Sub-question 3, second model: does happiness predict the growth of healthy life?

Run:      cd Code && uv run python 08_sq3b_life_expectancy.py
Reads:    Code/outputs/consecutive_pairs.csv
Produces: Code/outputs/sq3b_life_expectancy.md
          Code/outputs/figures/{,dark/}sq3b_life_expectancy.png

Model, as specified by the user - the mirror of the happiness-growth model:

    dE = k + a1 E + a2 E^2 + a3 H + e

where H is happiness and E is healthy life expectancy in years.

A warning that belongs at the top rather than in a footnote. The outcome here is the
year-on-year change in healthy life expectancy, and WHR interpolates and extrapolates
that series across the whole period. This script therefore begins by testing whether dE
is measurement at all before reporting any coefficient, because if the outcome is the
slope of an interpolation then a fitted relationship describes the interpolation and not
the world.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm

import viz_style as vs

CODE_DIR = Path(__file__).resolve().parent
OUTPUTS = CODE_DIR / "outputs"
SOURCE = OUTPUTS / "consecutive_pairs.csv"

COUNTRY = "Country name"
E_T, E_T1 = "Healthy life expectancy at birth_t", "Healthy life expectancy at birth_t1"

TERM_LABELS = ["$a_1$ — $E_t$", "$a_2$ — $E_t^2$", "$a_3$ — $H_t$"]
TERMS = ["E", "E2", "H"]

lines: list[str] = []


def out(text: str = "") -> None:
    lines.append(text)


def table(df: pd.DataFrame) -> None:
    lines.append("")
    lines.append(df.to_markdown(index=False))
    lines.append("")


def fit(d: pd.DataFrame, cols: list[str]):
    X = sm.add_constant(d[cols].to_numpy())
    return sm.OLS(d["dE"].to_numpy(), X).fit(
        cov_type="cluster", cov_kwds={"groups": d[COUNTRY].to_numpy()})


# Vertical limits for the change axis. A handful of points lie far outside and would
# otherwise flatten everything else into a band; the count excluded is reported on the
# figure rather than left for a reader to notice.
DE_LIM = (-0.5, 1.5)


def figure(d: pd.DataFrame, res, theme_name: str) -> None:
    t = vs.use(theme_name)
    k, a1, a2, a3 = res.params
    fig, ax = plt.subplots(figsize=(7.8, 5.0))
    ax.axhline(0, color=t.baseline, lw=0.9, zorder=1)
    ax.scatter(d["E"], d["dE"], s=14, color=t.muted, alpha=0.35, linewidths=0, zorder=2)
    xs = np.linspace(d["E"].min(), d["E"].max(), 100)
    for i, q in enumerate([0.1, 0.5, 0.9]):
        H = d["H"].quantile(q)
        ax.plot(xs, k + a1 * xs + a2 * xs ** 2 + a3 * H,
                color=t.series[i], lw=2.0, zorder=4,
                label=f"{H:.1f} ({int(q * 100)}th pct)")
    ax.legend(title="Happiness at year $t$", loc="upper right", alignment="left")
    ax.set_ylim(*DE_LIM)
    n_out = int(((d["dE"] < DE_LIM[0]) | (d["dE"] > DE_LIM[1])).sum())
    ax.set_xlabel("Healthy life expectancy at birth, year $t$ (years)")
    ax.set_ylabel("Change in healthy life expectancy, $t$ to $t+1$ (years)")
    vs.header(fig, "Happiness does not detectably predict health gains here")
    vs.source_note(fig, "Source: World Happiness Report 2024 underlying panel "
                        "(Helliwell et al., 2024a). OLS, standard errors clustered "
                        "by country. See the appendix on why this fit is not "
                        "interpretable as a relationship in the world.")
    vs.layout(fig, top=0.93)
    vs.save(fig, "sq3b_life_expectancy")


def main() -> int:
    d = pd.read_csv(SOURCE)
    d["dE"] = d[E_T1] - d[E_T]
    d["E2"] = d["E"] ** 2

    out("# Sub-question 3, second model — the growth of healthy life expectancy")
    out()
    out("$$\\Delta E = k + a_1 E_t + a_2 E_t^2 + a_3 H_t + \\varepsilon$$")
    out()
    out("Generated by `Code/08_sq3b_life_expectancy.py`. The mirror of the "
        "happiness-growth model: it asks whether happiness predicts how fast healthy "
        "life expectancy rises, which is the reverse direction of sub-question 1.")

    # ------------------------------------------------- the outcome is not measured
    out()
    out("## First: is $\\Delta E$ a measurement?")
    out()
    out("This has to come before any coefficient, because the answer determines what a "
        "coefficient could mean. WHR interpolates and extrapolates healthy life "
        "expectancy across the whole period, and differencing an interpolation returns "
        "its slope, not a measured change.")
    out()
    n_all = int(d["dE"].round(6).nunique())
    per = d.groupby(COUNTRY)["dE"].apply(lambda s: s.round(6).nunique())
    cnt = d.groupby(COUNTRY).size()
    out(f"- $\\Delta E$ takes only **{n_all} distinct values across {len(d):,} "
        f"country-years**.")
    out(f"- Per country, the median is **{int(per.median())} distinct values** across a "
        f"median of {int(cnt.median())} pairs. **{int((per <= 3).sum())} of "
        f"{len(per)} countries** have three or fewer.")

    gm = d.groupby(COUNTRY)["dE"].transform("mean")
    share_between_E = float(np.var(gm) / np.var(d["dE"]))
    gm2 = d.groupby(COUNTRY)["dH"].transform("mean")
    share_between_H = float(np.var(gm2) / np.var(d["dH"]))
    out(f"- **{share_between_E:.0%} of the variance in $\\Delta E$ is between "
        f"countries** rather than within them — it is close to a country-specific "
        f"constant. For $\\Delta H$ the same figure is {share_between_H:.0%}, so "
        "happiness genuinely moves from year to year and healthy life expectancy, as "
        "recorded here, does not.")
    out()
    out("The series themselves make it plainest:")
    out()
    ex = []
    for c in ("Japan", "Brazil", "Kenya"):
        s = d[d[COUNTRY] == c].sort_values("year_t")
        if not s.empty:
            ex.append({"country": c,
                       "$\\Delta E$, year by year":
                           " ".join(f"{v:+.2f}" for v in s["dE"])})
    table(pd.DataFrame(ex))
    out("Japan gains exactly 0.12 years of healthy life every year for sixteen years. "
        "Kenya gains exactly 0.52 for eight years and then exactly 0.40 for eight "
        "more. These are the gradients of straight lines drawn between anchor points, "
        "not annual observations.")

    # ---------------------------------------------------------------- the fit
    res = fit(d, TERMS)
    ci = res.conf_int()
    out()
    out("## The fit, as requested")
    out()
    table(pd.DataFrame({
        "term": ["$k$ (constant)"] + TERM_LABELS,
        "estimate": [round(v, 6) for v in res.params],
        "95% low": [round(v, 6) for v in ci[:, 0]],
        "95% high": [round(v, 6) for v in ci[:, 1]],
        "p": [f"{v:.3g}" for v in res.pvalues],
    }))
    out(f"- n = {int(res.nobs):,} pairs, clustered on {d[COUNTRY].nunique()} "
        f"countries. R² = {res.rsquared:.4f}.")
    fstat = res.f_test(np.eye(4)[1:])
    out(f"- Joint test that $a_1 = a_2 = a_3 = 0$: F = {float(fstat.fvalue):.2f}, "
        f"p = {float(fstat.pvalue):.3g}.")
    out()
    a3, lo, hi = res.params[3], ci[3, 0], ci[3, 1]
    direction = "positive" if a3 > 0 else "negative"
    excl = "excludes" if (lo > 0 or hi < 0) else "includes"
    out(f"Taken at face value, $a_3$ is **{a3:+.4f}** years of healthy life per year, "
        f"per point of happiness (95% CI {lo:+.4f} to {hi:+.4f}) — {direction}, with an "
        f"interval that {excl} zero.")

    # -------------------------------------------------- what it cannot mean
    out()
    out("## How to read the null")
    out()
    out(f"The R² of {res.rsquared:.2f} is not evidence of a good model. It comes almost "
        "entirely from $E$ and $E^2$, which track the interpolation's own structure. "
        "Happiness adds essentially nothing.")
    out()
    out("**The null on $a_3$ is uninformative, not reassuring.** It should not be read "
        "as evidence that happiness does not lengthen healthy life. An outcome that is "
        f"{share_between_E:.0%} country-constant carries very little year-on-year "
        "signal for anything to predict, so the test has little power to detect a real "
        "effect. Absence of evidence here is close to absence of a measurement.")
    out()
    out("Three specific problems, any one of which would be enough to withhold a "
        "conclusion:")
    out()
    out(f"1. **The outcome barely varies within a country.** With "
        f"{share_between_E:.0%} of its variance between countries, this is close to a "
        "cross-sectional regression of a country's average interpolated gain on its "
        "happiness level, even though the specification is dynamic. It does not use the "
        "year-on-year information the specification appears to use.")
    out("2. **Serial dependence is extreme, not merely present.** A country repeating "
        "one value for eight years contributes eight rows carrying the information of "
        "one. Clustering by country widens the intervals correctly for that, but it "
        "cannot recover information the data does not hold.")
    out("3. **Direction would not be identified even with a clean outcome.** Happier "
        "countries are richer, better governed and better served medically. Nothing "
        "here separates happiness from what accompanies it.")
    out()
    out("**On the apparent asymmetry.** Healthy life expectancy predicts the growth of "
        "happiness, while happiness does not detectably predict the growth of healthy "
        "life expectancy. The asymmetry follows from **which variable each model has "
        "to predict**, not from any asymmetry in the world.")
    out()
    out(f"- The first model's outcome is the change in happiness, a survey "
        f"measurement: {share_between_H:.0%} of its variance lies between countries, "
        f"so {1 - share_between_H:.0%} lies within them.")
    out(f"- The second model's outcome is the change in healthy life expectancy, which "
        f"the source interpolates: {share_between_E:.0%} of its variance lies between "
        f"countries, leaving {1 - share_between_E:.0%} within, and it takes {n_all} "
        f"distinct values across {len(d):,} country-years.")
    out()
    out("An outcome that is close to a per-country constant cannot be predicted by any "
        "regressor. The second model would return a null whether or not happiness "
        "lengthens healthy life, so the two results cannot be compared as though both "
        "tests were equally able to detect an effect.")
    out()
    out(f"The two R² values invite the same mistake in reverse: {res.rsquared:.2f} here "
        "against 0.07 for the happiness model makes this one look better specified, "
        "when its R² comes almost entirely from $E$ and $E^2$ tracing the "
        "interpolation's own structure.")
    out()
    out("The corresponding model for happiness does not share this defect: there the "
        "interpolated variable sits on the right-hand side as a level, and the outcome "
        "is the survey measure, which genuinely moves.")

    out()
    out("## Figure")
    out()
    out("![sq3b_life_expectancy](figures/sq3b_life_expectancy.png)")
    out()
    n_out = int(((d["dE"] < DE_LIM[0]) | (d["dE"] > DE_LIM[1])).sum())
    outs = d[(d["dE"] < DE_LIM[0]) | (d["dE"] > DE_LIM[1])]
    out("*The horizontal runs of points are the interpolation showing through: a "
        "country contributes the same value year after year. The fitted lines are the "
        "model above.*")
    out()
    out(f"The vertical axis is limited to {DE_LIM[0]} to {DE_LIM[1]} years, which "
        f"excludes **{n_out} of {len(d):,} points** ({n_out / len(d):.1%}) — "
        + ", ".join(f"{n} ({c})" for c, n in
                    outs.groupby(COUNTRY).size().sort_values(ascending=False)
                    .items()) + ". Without the limit those few points stretch the axis "
        "to ±5 years and compress everything else into an unreadable band. Both sets "
        "are themselves interpolation: the source steps Syria down by exactly 1.76 "
        "years annually, and Haiti up by exactly 5.32.")
    table(outs[[COUNTRY, "year_t", "dE"]].round(2)
              .rename(columns={COUNTRY: "Country", "year_t": "Start year",
                               "dE": "$\\Delta E$"}))

    import json
    (OUTPUTS / "sq3b_coefficients.json").write_text(json.dumps({
        "model": "dE = k + a1*E + a2*E^2 + a3*H",
        "k": float(res.params[0]), "a1": float(res.params[1]),
        "a2": float(res.params[2]), "a3": float(res.params[3]),
        "n": int(res.nobs), "countries": int(d[COUNTRY].nunique()),
    }, indent=2) + "\n")

    for name in ("light", "dark"):
        figure(d, res, name)

    path = OUTPUTS / "sq3b_life_expectancy.md"
    path.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
